exclude:
- /getting_started.md
- /package-lock.json
- /Vagrantfile
- /devserver.md
- /LICENSE
- /package.json
- /README.md
- /boot-image/.*
- /sample-audio/.*
- /node_modules/.*
- /vivado-boards/.*
- /docs/.*
- /vagrant/.*
- /pl/.*
- /mb/Cora-Z7-07S /.*
- /mb/drm_audio_fw_bsp/.*
- /mb/README.md
- /mb/system_wrapper.hdf
languages:
- cpp
- python
