# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
# IP: The module: 'system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
# IP: The module: 'system_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
