# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0.xci
# IP: The module: 'system_mdm_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0.xci
# IP: The module: 'system_mdm_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_mdm_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
