# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /ectf_master/pl/src/bd/system/ip/system_auto_pc_6/system_auto_pc_6.xci
# IP: The module: 'system_auto_pc_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf_master/pl/src/bd/system/ip/system_auto_pc_6/system_auto_pc_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /ectf_master/pl/src/bd/system/ip/system_auto_pc_6/system_auto_pc_6.xci
# IP: The module: 'system_auto_pc_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf_master/pl/src/bd/system/ip/system_auto_pc_6/system_auto_pc_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
