# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /ectf/pl/src/bd/system/ip/system_auto_pc_4/system_auto_pc_4.xci
# IP: The module: 'system_auto_pc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf/pl/src/bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /ectf/pl/src/bd/system/ip/system_auto_pc_4/system_auto_pc_4.xci
# IP: The module: 'system_auto_pc_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf/pl/src/bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
