# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /ectf/pl/proj/test/bd/system/ip/system_xbar_1/system_xbar_1.xci
# IP: The module: 'system_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf/pl/proj/test/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /ectf/pl/proj/test/bd/system/ip/system_xbar_1/system_xbar_1.xci
# IP: The module: 'system_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf/pl/proj/test/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
