# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z007sclg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /ectf_master/pl/proj/test/test.cache/wt [current_project]
set_property parent.project_path /ectf_master/pl/proj/test/test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths /ectf_master/pl/repo [current_project]
set_property ip_output_repo /ectf_master/pl/repo/cache [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /ectf_master/pl/src/bd/system/hdl/system_wrapper.vhd
add_files /ectf_master/pl/src/bd/system/system.bd
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_blk_mem_gen_0_0/system_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_clk_wiz_25M_0/system_clk_wiz_25M_0_board.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_clk_wiz_25M_0/system_clk_wiz_25M_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_clk_wiz_25M_0/system_clk_wiz_25M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_data_lmb_bram_if_cntlr_1_0/system_data_lmb_bram_if_cntlr_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_data_lmb_v10_1_0/system_data_lmb_v10_1_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_data_lmb_v10_1_0/system_data_lmb_v10_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_dma_axi_bram_ctrl_1_0/system_dma_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_dma_blk_mem_gen_1_0/system_dma_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_fifo_count_axi_gpio_0_0/system_fifo_count_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_fifo_count_axi_gpio_0_0/system_fifo_count_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_fifo_count_axi_gpio_0_0/system_fifo_count_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_ins_lmb_bram_if_cntlr_0_0/system_ins_lmb_bram_if_cntlr_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_ins_lmb_v10_0_0/system_ins_lmb_v10_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_ins_lmb_v10_0_0/system_ins_lmb_v10_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_int_axi_gpio_0_0/system_int_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_int_axi_gpio_0_0/system_int_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_int_axi_gpio_0_0/system_int_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_mb_dma_axi_bram_ctrl_0_0/system_mb_dma_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_mdm_0_0/system_mdm_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_share_axi_bram_ctrl_0_0/system_share_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_share_axi_bram_ctrl_1_0/system_share_axi_bram_ctrl_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_share_blk_mem_gen_1_0/system_share_blk_mem_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_proc_sys_reset_1_0/system_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_9/system_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_8/system_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_7/system_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_10/system_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_cc_2/system_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_cc_2/system_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_cc_2/system_auto_cc_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_cc_1/system_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_cc_1/system_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_cc_1/system_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_6/system_auto_pc_6_ooc.xdc]
set_property used_in_synthesis false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/ip/system_auto_pc_5/system_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /ectf_master/pl/src/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /ectf_master/pl/src/constraints/Cora-Z7-Master.xdc
set_property used_in_implementation false [get_files /ectf_master/pl/src/constraints/Cora-Z7-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z007sclg400-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
