# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xci
# IP: The module: 'system_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xci
# IP: The module: 'system_microblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Benjamin/Downloads/eCTF20-datapath-changes-edit/eCTF20-datapath-changes/pl/proj/test/bd/system/ip/system_microblaze_0_0/system_microblaze_0_0_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
