webtalk_init -webtalk_dir /ectf/pl/proj/test/test.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-02-17 20:46:29" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2r66abb0cthjvhuc4c04r1apmk" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Arch" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Arch Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 3900X 12-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2110.090 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.799 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1581993954000" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key Device -value "7z007s" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1581993954000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1581993989950"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1581993989950"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1581993989950"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1581993989950"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1581993989950"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1581993989950"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1581993989950"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1581993989950"
webtalk_transmit -clientid 854331275 -regid "" -xml /ectf/pl/proj/test/test.sdk/webtalk/usage_statistics_ext_sdk.xml -html /ectf/pl/proj/test/test.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /ectf/pl/proj/test/test.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
