#!/usr/bin/env python3
"""
Description: Generates system wide secrets containing all potential regions
Use: Once per ecosystem of devices
"""
import json
from argparse import ArgumentParser
from nacl import utils, public, secret


def main(region_dict, file_name):
    try:
        secrets = open(file_name, "w")
    except Exception as e:
        print("Unable to open secrets file: %s" % (e,))
        return 0

    info = json.dumps(region_dict, indent=4, sort_keys=True)
    secrets.write(info)
    secrets.close()


def get_args():
    """gets arguments from command line"""
    parser = ArgumentParser(description='main interface to provision system')
    parser.add_argument('--region-list', help='list of regions for provisioning purposes',
                        required=True, nargs='+')
    parser.add_argument('--outfile', help='file to save region secrets to', required=True)
    args = parser.parse_args()
    return args.region_list, args.outfile


if __name__ == '__main__':
    region_list, outfile = get_args()
    print("generating system specific secrets")
    regions = {}
    for r in region_list:
        # create a public / private key pair (Curve25519)
        pvt_key = public.PrivateKey.generate()
        regions[r] = {"pub_key": bytes(pvt_key).hex(),                  # to convert .hex() back to bytes bytes.fromhex(salt-as-hex)
                      "priv_key": bytes(pvt_key).hex(),
                      "priv_key_enc": "",
                      "rand_pass": utils.random(10).hex(),         
                      }                  
    main(regions, outfile)