# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /ectf_dev/ectf/eCTF20/pl/proj/test/bd/system/ip/system_auto_pc_9/system_auto_pc_9.xci
# IP: The module: 'system_auto_pc_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf_dev/ectf/eCTF20/pl/proj/test/bd/system/ip/system_auto_pc_9/system_auto_pc_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /ectf_dev/ectf/eCTF20/pl/proj/test/bd/system/ip/system_auto_pc_9/system_auto_pc_9.xci
# IP: The module: 'system_auto_pc_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /ectf_dev/ectf/eCTF20/pl/proj/test/bd/system/ip/system_auto_pc_9/system_auto_pc_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
