name: clang-format lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: './mb/drm_audio_fw/src'
        extensions: 'c,h'
        clangFormatVersion: 9
